# Generated by Django 5.2.8 on 2026-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('material', models.CharField(max_length=20)),
                ('clothing_type', models.CharField(max_length=20)),
                ('clothing_color', models.CharField(max_length=20)),
                ('clothing_size', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=7)),
                ('care', models.CharField(max_length=100)),
            ],
        ),
    ]
