# Generated by Django 5.2.8 on 2026-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_bash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.FilePathField(default=76),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=9898, upload_to=''),
            preserve_default=False,
        ),
    ]
