# Generated by Django 5.2.8 on 2026-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_bash_app', '0002_item_description_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dop_info',
            field=models.TextField(default=34),
            preserve_default=False,
        ),
    ]
