# Generated by Django 5.2.8 on 2026-01-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_bash_app', '0003_item_dop_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
