# Generated by Django 5.2.8 on 2026-05-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_bash_app', '0004_remove_item_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='clothing_type',
            field=models.CharField(choices=[('headwear', 'головные уборы'), ('t-shirt', 'футболка'), ('underwear', 'штаны'), ('sweater', 'свитера'), ('boots', 'ботинки'), ('gloves', 'перчатки'), ('socks', 'носки')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
